# Generated by wrkenv - Simple activation script

# Activate the workenv
& workenv\wrkenv_darwin_arm64\Scripts\Activate.ps1

Write-Host "✅ Activated wrkenv: wrkenv_darwin_arm64" -ForegroundColor Green
Write-Host "   Python: $(Get-Command python | Select-Object -ExpandProperty Source)"
Write-Host "   wrkenv: $(Get-Command wrkenv | Select-Object -ExpandProperty Source)"
