# Generated by wrknv - Simple activation script

# Activate the workenv
& workenv\wrknv_darwin_arm64\Scripts\Activate.ps1

Write-Host "✅ Activated wrknv: wrknv_darwin_arm64" -ForegroundColor Green
Write-Host "   Python: $(Get-Command python | Select-Object -ExpandProperty Source)"
Write-Host "   wrknv: $(Get-Command wrknv | Select-Object -ExpandProperty Source)"
