project_name = "wrknv"
version = "0.1.0"
log_level = "INFO"

[tools]
# Matrix tool configurations
terraform = ["1.11.x", "1.13.x"]
tofu = ["1.9.x", "1.10.x"]
# go = { version = "1.21.0" }

[tools.bao]
version = "2.1.0"

[gitignore]
templates = ["Python", "Node", "Global"]

[container]
enabled = false

[package]
# Example package configuration
# name = "my-provider"
# version = "0.1.0"
# entry_point = "src/my_provider/__init__.py"
