project_name = "wrknv"
version = "0.1.0"

[tools]
terraform = [
    "1.11.x",
    "1.13.x",
]
tofu = [
    "1.9.x",
    "1.10.x",
]

[tools.bao]
version = "2.1.0"

[profiles.dev]
terraform = [
    "1.11.x",
    "1.13.x",
]
tofu = [
    "1.9.x",
    "1.10.x",
]
bao = "2.1.0"

[workenv]
auto_install = true
use_cache = true
cache_ttl = "7d"
log_level = "WARNING"
container_runtime = "docker"
container_registry = "ghcr.io"

[env]
